# Generated by Django 3.1.5 on 2021-02-15 06:14

from django.db import migrations, models
import photo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=50)),
                ('longtitude', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=200, null=True)),
                ('author', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to=photo.models.user_directory_path)),
            ],
        ),
    ]
