# Generated by Django 3.1.5 on 2021-01-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lattitude', models.CharField(max_length=30)),
                ('longtitude', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='<django.db.models.fields.CharField>/<django.db.models.fields.CharField>')),
            ],
        ),
    ]
