# Generated by Django 3.1.6 on 2021-02-08 03:04

from django.db import migrations, models
import photo.models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='lattitude',
            new_name='latitude',
        ),
        migrations.AlterField(
            model_name='point',
            name='image',
            field=models.ImageField(upload_to=photo.models.user_directory_path),
        ),
    ]
